[package]
name = "lua_engine"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
logic = { path = "../logic" }
mlua = { version = "0.10.3", features = ["luau"] }
tokio = "1.44.1"
[build-dependencies]
regex = "1.11.1"
